general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N16"
stages:
  Build:
    npmExecuteLint: false
  "Additional Unit Tests":
    npmExecuteScripts: true
    scriptOptions:
      - "test"
  Release:
    cloudFoundryDeploy: false
